spring:
  application:
    name: "Config server"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//Bhardwaj//eazybytes//Documents//config"
        git:
          uri: "https://github.com/Ashutosh4Kumar/banking-configuration.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: "Ashutosh4Kumar"
          
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071
encrypt:
  key: "05021989090219822102018"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

